import { Property } from './types';

export const sampleProperties: Property[] = [
  {
    id: 'golden-haven',
    title: 'Golden Haven Estate',
    location: 'Ibeju-Lekki, Lagos',
    price: '₦3,000,000',
    imageUrl: '/lovable-uploads/Golden.png',
    propertyType: 'Residential',
    sqm: 600,
    totalPlots: 120,
    availablePlots: 75,
    pricePerPlot: 3000000,
    description: 'A serene residential estate in the heart of Ibeju-Lekki, offering a blend of luxury and comfort.',
    features: ['Perimeter Fencing', 'Gatehouse', 'Good Road Network', 'Drainage System'],
    amenities: ['Recreational Park', 'Street Lights', 'Green Areas', 'Security Patrol'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
  {
    id: 'royal-city',
    title: 'Royal City Estate',
    location: 'Epe, Lagos',
    price: '₦2,000,000',
    imageUrl: '/lovable-uploads/Royalcity.png',
    propertyType: 'Residential',
    sqm: 500,
    totalPlots: 150,
    availablePlots: 60,
    pricePerPlot: 2000000,
    description: 'An exquisite residential estate in Epe, designed for those who appreciate elegance and tranquility.',
    features: ['24/7 Security', 'Good Road Network', 'Electricity', 'Water Supply'],
    amenities: ['School', 'Hospital', 'Shopping Mall', 'Recreational Center'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan']
  },
  {
    id: 'diamond-resort',
    title: 'Diamond Resort Estate',
    location: 'Owerri, Imo State',
    price: '₦2,800,000',
    imageUrl: '/lovable-uploads/Diamond.png',
    propertyType: 'Commercial',
    sqm: 700,
    totalPlots: 80,
    availablePlots: 30,
    pricePerPlot: 2800000,
    description: 'A premium commercial estate in Owerri, ideal for businesses seeking a strategic location.',
    features: ['Ample Parking Space', 'Perimeter Fencing', 'Centralized Security', 'Backup Generator'],
    amenities: ['Conference Center', 'Business Lounge', 'High-Speed Internet', 'Restaurant'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
  {
    id: 'emerald-island',
    title: 'Emerald Island Estate',
    location: 'Port Harcourt, Rivers State',
    price: '₦3,200,000',
    imageUrl: '/lovable-uploads/Emerald.png',
    propertyType: 'Residential',
    sqm: 550,
    totalPlots: 100,
    availablePlots: 40,
    pricePerPlot: 3200000,
    description: 'A luxurious residential estate in Port Harcourt, offering a serene and upscale living environment.',
    features: ['Gated Community', 'Landscaping', 'Street Lights', 'Waste Management'],
    amenities: ['Swimming Pool', 'Gym', 'Clubhouse', 'Children\'s Play Area'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan']
  },
  {
    id: 'the-boulevard',
    title: 'The Boulevard Estate',
    location: 'Abuja, FCT',
    price: '₦3,500,000',
    imageUrl: '/lovable-uploads/Boulevard.png',
    propertyType: 'Commercial',
    sqm: 800,
    totalPlots: 60,
    availablePlots: 20,
    pricePerPlot: 3500000,
    description: 'A prestigious commercial estate in Abuja, perfect for establishing a strong business presence.',
    features: ['Excellent Road Network', '24/7 Power Supply', 'High Security', 'Modern Infrastructure'],
    amenities: ['Banking Facilities', 'Shopping Complex', 'Food Court', 'Office Spaces'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
  {
    id: 'precious-gardens',
    title: 'Precious Gardens Estate',
    location: 'Sagamu, Ogun State',
    price: '₦2,500,000',
    imageUrl: '/lovable-uploads/Precious.png',
    propertyType: 'Residential',
    sqm: 500,
    totalPlots: 100,
    availablePlots: 0, // SOLD OUT
    pricePerPlot: 2500000,
    description: 'A premium residential estate in Sagamu with modern amenities and excellent infrastructure.',
    features: ['24/7 Security', 'Good Road Network', 'Electricity', 'Water Supply'],
    amenities: ['Swimming Pool', 'Playground', 'Shopping Mall', 'Hospital'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan']
  },
  {
    id: 'sunflower-city',
    title: 'Sunflower City Estate',
    location: 'Benin, Edo State',
    price: '₦1,800,000',
    imageUrl: '/lovable-uploads/Sunflower.png',
    propertyType: 'Residential',
    sqm: 450,
    totalPlots: 200,
    availablePlots: 120,
    pricePerPlot: 1800000,
    description: 'A vibrant residential estate in Benin, offering affordable and comfortable living spaces.',
    features: ['Well-Planned Layout', 'Green Spaces', 'Recreational Facilities', 'Security'],
    amenities: ['School', 'Market', 'Clinic', 'Community Center'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan']
  },
  {
    id: 'harmony-villas',
    title: 'Harmony Villas Estate',
    location: 'Kano, Kano State',
    price: '₦2,200,000',
    imageUrl: '/lovable-uploads/Harmony.png',
    propertyType: 'Residential',
    sqm: 500,
    totalPlots: 90,
    availablePlots: 50,
    pricePerPlot: 2200000,
    description: 'A peaceful residential estate in Kano, designed for family living with essential amenities.',
    features: ['Perimeter Fence', 'Gatehouse', 'Good Road Network', 'Drainage System'],
    amenities: ['Park', 'Street Lights', 'Water Supply', 'Security Patrol'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
  {
    id: 'grand-view',
    title: 'Grand View Estate',
    location: 'Enugu, Enugu State',
    price: '₦2,700,000',
    imageUrl: '/lovable-uploads/Grandview.png',
    propertyType: 'Residential',
    sqm: 550,
    totalPlots: 110,
    availablePlots: 65,
    pricePerPlot: 2700000,
    description: 'A scenic residential estate in Enugu, offering beautiful views and a comfortable lifestyle.',
    features: ['24/7 Security', 'Good Road Network', 'Electricity', 'Water Supply'],
    amenities: ['School', 'Hospital', 'Shopping Mall', 'Recreational Center'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan']
  },
  {
    id: 'city-lights',
    title: 'City Lights Estate',
    location: 'Kaduna, Kaduna State',
    price: '₦2,900,000',
    imageUrl: '/lovable-uploads/Citylight.png',
    propertyType: 'Commercial',
    sqm: 650,
    totalPlots: 70,
    availablePlots: 25,
    pricePerPlot: 2900000,
    description: 'A modern commercial estate in Kaduna, ideal for businesses looking for a prime location.',
    features: ['Ample Parking Space', 'Perimeter Fencing', 'Centralized Security', 'Backup Generator'],
    amenities: ['Conference Center', 'Business Lounge', 'High-Speed Internet', 'Restaurant'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
];
