
import { Property } from './types';

import luxury3BedroomLagos from '@/assets/luxury-3bedroom-lagos.jpg';
import luxury4BedroomAsaba from '@/assets/luxury-4bedroom-asaba.jpg';
import luxurySemiDetachedOgun from '@/assets/luxury-semi-detached-ogun.jpg';
import luxuryTerraceLagos from '@/assets/luxury-terrace-lagos.jpg';
import luxuryDetachedAsaba from '@/assets/luxury-detached-asaba.jpg';
import luxuryRentalOgun from '@/assets/luxury-rental-ogun.jpg';

export const sampleProperties: Property[] = [
  // Luxury Home Sales and Rentals - Updated prices based on market data
  {
    id: 'luxury-3bedroom-lagos',
    name: 'Premium 3-Bedroom House Lagos',
    title: 'Luxury 3-Bedroom House in Victoria Island',
    location: 'Victoria Island, Lagos',
    price: '₦180,000,000',
    imageUrl: luxury3BedroomLagos,
    propertyType: 'Residential House',
    property_category: 'home',
    size: 250,
    sqm: 250,
    totalPlots: 1,
    availablePlots: 1,
    pricePerPlot: 180000000,
    description: 'Stunning 3-bedroom house in the heart of Victoria Island. Features modern finishes, spacious living areas, fitted kitchen, and excellent security. Perfect for both purchase and rental.',
    features: ['3 Bedrooms', '3 Bathrooms', 'Modern Kitchen', 'Security System', 'Parking Space'],
    amenities: ['Swimming Pool', 'Gym', 'Garden', '24/7 Security', 'Generator'],
    paymentPlans: ['Outright Payment', 'Mortgage Available', '12 Months Plan']
  },
  {
    id: 'luxury-4bedroom-asaba',
    name: 'Elegant 4-Bedroom Duplex Asaba',
    title: 'Luxurious 4-Bedroom Duplex in GRA Asaba',
    location: 'GRA, Asaba, Delta State',
    price: '₦160,000,000',
    imageUrl: luxury4BedroomAsaba,
    propertyType: 'Residential House',
    property_category: 'home',
    size: 300,
    sqm: 300,
    totalPlots: 1,
    availablePlots: 1,
    pricePerPlot: 160000000,
    description: 'Beautiful 4-bedroom duplex in the prestigious GRA area of Asaba. Boasts contemporary design, master ensuite, family lounge, and ample parking space.',
    features: ['4 Bedrooms', '4 Bathrooms', 'Family Lounge', 'Master Ensuite', 'Ample Parking'],
    amenities: ['Quiet Neighborhood', 'Good Road Network', 'Electricity', 'Water Supply'],
    paymentPlans: ['Outright Payment', 'Mortgage Available', '18 Months Plan']
  },
  {
    id: 'luxury-semi-detached-ogun',
    name: 'Semi-Detached Duplex Ogun',
    title: 'Modern Semi-Detached Duplex in Mowe',
    location: 'Mowe, Ogun State',
    price: '₦130,000,000',
    imageUrl: luxurySemiDetachedOgun,
    propertyType: 'Residential House',
    property_category: 'home',
    size: 280,
    sqm: 280,
    totalPlots: 1,
    availablePlots: 1,
    pricePerPlot: 130000000,
    description: 'Exquisite semi-detached duplex in a serene environment in Mowe. Features include spacious bedrooms, modern kitchen, and beautiful compound.',
    features: ['4 Bedrooms', '3 Bathrooms', 'Modern Kitchen', 'Beautiful Compound', 'Semi-Detached'],
    amenities: ['Gated Estate', 'Security', 'Good Road', 'Electricity'],
    paymentPlans: ['Outright Payment', 'Mortgage Available', '12 Months Plan']
  },
  {
    id: 'luxury-terrace-lagos',
    name: 'Luxury Terrace Houses Lagos',
    title: 'Premium Terrace Houses in Lekki',
    location: 'Lekki, Lagos',
    price: '₦240,000,000',
    imageUrl: luxuryTerraceLagos,
    propertyType: 'Residential House',
    property_category: 'home',
    size: 220,
    sqm: 220,
    totalPlots: 1,
    availablePlots: 1,
    pricePerPlot: 240000000,
    description: 'Sophisticated terrace houses in the exclusive Lekki area. Contemporary design with top-notch finishes, close to major amenities and business districts.',
    features: ['3 Bedrooms', '3 Bathrooms', 'Terrace Design', 'Contemporary Finishes', 'Prime Location'],
    amenities: ['Close to VI', 'Shopping Malls', 'Good Schools', 'Business Districts'],
    paymentPlans: ['Outright Payment', 'Mortgage Available', '15 Months Plan']
  },
  {
    id: 'luxury-detached-asaba',
    name: 'Detached Duplex Mansion Asaba',
    title: 'Magnificent Detached Duplex in Asaba',
    location: 'Cable Point, Asaba, Delta State',
    price: '₦600,000,000',
    imageUrl: luxuryDetachedAsaba,
    propertyType: 'Residential House',
    property_category: 'home',
    size: 400,
    sqm: 400,
    totalPlots: 1,
    availablePlots: 1,
    pricePerPlot: 600000000,
    description: 'Magnificent detached duplex mansion in the upscale Cable Point area. Features include 5 bedrooms, guest rooms, study, swimming pool area, and expansive compound.',
    features: ['5 Bedrooms', '5 Bathrooms', 'Guest Rooms', 'Study Room', 'Swimming Pool'],
    amenities: ['Expansive Compound', 'Premium Location', 'Luxury Finishes', 'Privacy'],
    paymentPlans: ['Outright Payment', 'Mortgage Available', '24 Months Plan']
  },
  {
    id: 'luxury-rental-ogun',
    name: 'Luxury Rental Apartments Ogun',
    title: 'Modern 3-Bedroom Apartments for Rent',
    location: 'Arepo, Ogun State',
    price: '₦95,000,000',
    imageUrl: luxuryRentalOgun,
    propertyType: 'Residential House',
    property_category: 'home',
    size: 180,
    sqm: 180,
    totalPlots: 1,
    availablePlots: 1,
    pricePerPlot: 95000000,
    description: 'Modern 3-bedroom apartments in a well-planned estate in Arepo. Perfect for families seeking quality residential accommodation with excellent facilities.',
    features: ['3 Bedrooms', '2 Bathrooms', 'Modern Fittings', 'Family Friendly', 'Estate Living'],
    amenities: ['Estate Facilities', 'Security', 'Parking', 'Good Roads'],
    paymentPlans: ['Outright Payment', 'Mortgage Available', '12 Months Plan']
  },
  {
    id: 'luxury-5bedroom-lekki',
    name: 'Luxury 5-Bedroom Duplex Lekki',
    title: 'Premium 5-Bedroom Fully Detached Duplex',
    location: 'Lekki, Lagos',
    price: '₦750,000,000',
    imageUrl: luxuryTerraceLagos,
    propertyType: 'Residential House',
    property_category: 'home',
    size: 500,
    sqm: 500,
    totalPlots: 1,
    availablePlots: 1,
    pricePerPlot: 750000000,
    description: 'Magnificent 5-bedroom fully detached duplex in prime Lekki location. Features swimming pool, modern amenities, and luxury finishes throughout.',
    features: ['5 Bedrooms', '5 Bathrooms', 'Swimming Pool', 'Luxury Finishes', 'Prime Location'],
    amenities: ['24/7 Security', 'Swimming Pool', 'Gym', 'Garden', 'Parking'],
    paymentPlans: ['Outright Payment', 'Mortgage Available', '24 Months Plan']
  },
  {
    id: 'luxury-4bedroom-ikoyi',
    name: 'Luxury 4-Bedroom Mansion Ikoyi',
    title: 'Elegant 4-Bedroom Mansion in Ikoyi',
    location: 'Ikoyi, Lagos',
    price: '₦1,200,000,000',
    imageUrl: luxury3BedroomLagos,
    propertyType: 'Residential House',
    property_category: 'home',
    size: 600,
    sqm: 600,
    totalPlots: 1,
    availablePlots: 1,
    pricePerPlot: 1200000000,
    description: 'Ultra-luxury 4-bedroom mansion in exclusive Ikoyi district. Premium location with world-class amenities and sophisticated design.',
    features: ['4 Bedrooms', '4 Bathrooms', 'Study Room', 'Guest Wing', 'Premium Finishes'],
    amenities: ['Prime Location', 'Security', 'Swimming Pool', 'Garden', 'Parking'],
    paymentPlans: ['Outright Payment', 'Mortgage Available', '36 Months Plan']
  },
  {
    id: 'golden-haven',
    name: 'Golden Haven Estate',
    title: 'Golden Haven Estate',
    location: 'Ibeju-Lekki, Lagos',
    price: '₦3,000,000',
    imageUrl: '/lovable-uploads/Golden.png',
    propertyType: 'Residential',
    size: 600,
    sqm: 600,
    totalPlots: 120,
    availablePlots: 75,
    pricePerPlot: 3000000,
    description: 'A serene residential estate in the heart of Ibeju-Lekki, offering a blend of luxury and comfort.',
    features: ['Perimeter Fencing', 'Gatehouse', 'Good Road Network', 'Drainage System'],
    amenities: ['Recreational Park', 'Street Lights', 'Green Areas', 'Security Patrol'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
  {
    id: 'royal-city',
    name: 'Royal City Estate',
    title: 'Royal City Estate',
    location: 'Epe, Lagos',
    price: '₦2,000,000',
    imageUrl: '/lovable-uploads/Royalcity.png',
    propertyType: 'Residential',
    size: 500,
    sqm: 500,
    totalPlots: 150,
    availablePlots: 60,
    pricePerPlot: 2000000,
    description: 'An exquisite residential estate in Epe, designed for those who appreciate elegance and tranquility.',
    features: ['24/7 Security', 'Good Road Network', 'Electricity', 'Water Supply'],
    amenities: ['School', 'Hospital', 'Shopping Mall', 'Recreational Center'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan']
  },
  {
    id: 'diamond-resort',
    name: 'Diamond Resort Estate',
    title: 'Diamond Resort Estate',
    location: 'Owerri, Imo State',
    price: '₦2,800,000',
    imageUrl: '/lovable-uploads/Diamond.png',
    propertyType: 'Commercial',
    size: 700,
    sqm: 700,
    totalPlots: 80,
    availablePlots: 30,
    pricePerPlot: 2800000,
    description: 'A premium commercial estate in Owerri, ideal for businesses seeking a strategic location.',
    features: ['Ample Parking Space', 'Perimeter Fencing', 'Centralized Security', 'Backup Generator'],
    amenities: ['Conference Center', 'Business Lounge', 'High-Speed Internet', 'Restaurant'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
  {
    id: 'emerald-island',
    name: 'Emerald Island Estate',
    title: 'Emerald Island Estate',
    location: 'Port Harcourt, Rivers State',
    price: '₦3,200,000',
    imageUrl: '/lovable-uploads/Emerald.png',
    propertyType: 'Residential',
    size: 550,
    sqm: 550,
    totalPlots: 100,
    availablePlots: 40,
    pricePerPlot: 3200000,
    description: 'A luxurious residential estate in Port Harcourt, offering a serene and upscale living environment.',
    features: ['Gated Community', 'Landscaping', 'Street Lights', 'Waste Management'],
    amenities: ['Swimming Pool', 'Gym', 'Clubhouse', 'Children\'s Play Area'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan']
  },
  {
    id: 'the-boulevard',
    name: 'The Boulevard Estate',
    title: 'The Boulevard Estate',
    location: 'Abuja, FCT',
    price: '₦3,500,000',
    imageUrl: '/lovable-uploads/Boulevard.png',
    propertyType: 'Commercial',
    size: 800,
    sqm: 800,
    totalPlots: 60,
    availablePlots: 20,
    pricePerPlot: 3500000,
    description: 'A prestigious commercial estate in Abuja, perfect for establishing a strong business presence.',
    features: ['Excellent Road Network', '24/7 Power Supply', 'High Security', 'Modern Infrastructure'],
    amenities: ['Banking Facilities', 'Shopping Complex', 'Food Court', 'Office Spaces'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
  {
    id: 'precious-gardens',
    name: 'Precious Gardens Estate',
    title: 'Precious Gardens Estate',
    location: 'Sagamu, Ogun State',
    price: '₦2,500,000',
    imageUrl: '/lovable-uploads/Precious.png',
    propertyType: 'Residential',
    size: 500,
    sqm: 500,
    totalPlots: 100,
    availablePlots: 0, // SOLD OUT
    pricePerPlot: 2500000,
    description: 'A premium residential estate in Sagamu with modern amenities and excellent infrastructure.',
    features: ['24/7 Security', 'Good Road Network', 'Electricity', 'Water Supply'],
    amenities: ['Swimming Pool', 'Playground', 'Shopping Mall', 'Hospital'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan']
  },
  {
    id: 'sunflower-city',
    name: 'Sunflower City Estate',
    title: 'Sunflower City Estate',
    location: 'Benin, Edo State',
    price: '₦1,800,000',
    imageUrl: '/lovable-uploads/Sunflower.png',
    propertyType: 'Residential',
    size: 450,
    sqm: 450,
    totalPlots: 200,
    availablePlots: 120,
    pricePerPlot: 1800000,
    description: 'A vibrant residential estate in Benin, offering affordable and comfortable living spaces.',
    features: ['Well-Planned Layout', 'Green Spaces', 'Recreational Facilities', 'Security'],
    amenities: ['School', 'Market', 'Clinic', 'Community Center'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan']
  },
  {
    id: 'harmony-villas',
    name: 'Harmony Villas Estate',
    title: 'Harmony Villas Estate',
    location: 'Kano, Kano State',
    price: '₦2,200,000',
    imageUrl: '/lovable-uploads/Harmony.png',
    propertyType: 'Residential',
    size: 500,
    sqm: 500,
    totalPlots: 90,
    availablePlots: 50,
    pricePerPlot: 2200000,
    description: 'A peaceful residential estate in Kano, designed for family living with essential amenities.',
    features: ['Perimeter Fence', 'Gatehouse', 'Good Road Network', 'Drainage System'],
    amenities: ['Park', 'Street Lights', 'Water Supply', 'Security Patrol'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
  {
    id: 'grand-view',
    name: 'Grand View Estate',
    title: 'Grand View Estate',
    location: 'Enugu, Enugu State',
    price: '₦2,700,000',
    imageUrl: '/lovable-uploads/Grandview.png',
    propertyType: 'Residential',
    size: 550,
    sqm: 550,
    totalPlots: 110,
    availablePlots: 65,
    pricePerPlot: 2700000,
    description: 'A scenic residential estate in Enugu, offering beautiful views and a comfortable lifestyle.',
    features: ['24/7 Security', 'Good Road Network', 'Electricity', 'Water Supply'],
    amenities: ['School', 'Hospital', 'Shopping Mall', 'Recreational Center'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan']
  },
  {
    id: 'city-lights',
    name: 'City Lights Estate',
    title: 'City Lights Estate',
    location: 'Kaduna, Kaduna State',
    price: '₦2,900,000',
    imageUrl: '/lovable-uploads/Citylight.png',
    propertyType: 'Commercial',
    size: 650,
    sqm: 650,
    totalPlots: 70,
    availablePlots: 25,
    pricePerPlot: 2900000,
    description: 'A modern commercial estate in Kaduna, ideal for businesses looking for a prime location.',
    features: ['Ample Parking Space', 'Perimeter Fencing', 'Centralized Security', 'Backup Generator'],
    amenities: ['Conference Center', 'Business Lounge', 'High-Speed Internet', 'Restaurant'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
];
