
import { Property } from './types';

import luxury3BedroomLagos from '@/assets/luxury-3bedroom-lagos.jpg';
import luxury4BedroomAsaba from '@/assets/luxury-4bedroom-asaba.jpg';
import luxurySemiDetachedOgun from '@/assets/luxury-semi-detached-ogun.jpg';
import luxuryTerraceLagos from '@/assets/luxury-terrace-lagos.jpg';
import luxuryDetachedAsaba from '@/assets/luxury-detached-asaba.jpg';
import luxuryRentalOgun from '@/assets/luxury-rental-ogun.jpg';

export const sampleProperties: Property[] = [
  // NEW FEATURED ESTATES - Latest Additions
  // Big League Haven 1 - New Addition
  {
    id: 'big-league-haven-1',
    name: 'The Big League Haven 1',
    title: 'The Big League Haven 1 - Premium Estate',
    location: 'Warri-Asaba Road, Ogwashi-Uku, Asaba, Delta State',
    price: '₦5,500,000',
    actualPrice: 7500000,
    prelaunchPrice: 5500000,
    imageUrl: '/lovable-uploads/BIG_league_Heaven_1.jpg',
    propertyType: 'Residential Land',
    property_category: 'land',
    size: 464,
    sqm: 464,
    totalPlots: 200,
    availablePlots: 175,
    pricePerPlot: 5500000,
    description: 'THE BIG LEAGUE HAVEN 1 – a prestigious estate located at Warri-Asaba Road, Ogwashi-Uku, Asaba, Delta State. Your golden opportunity to secure prime land in a fast-developing area with top-notch proposed estate features. Plot Size: 50ft x 100ft (464SQM), Freehold title.',
    features: ['Secure Perimeter Fencing', 'Good Road Network', 'Constant Power Supply', 'Portable Water System', 'Recreational & Green Areas'],
    amenities: ['Delta State Polytechnic Nearby', 'Admiralty University Access', 'Asaba International Airport', 'Asaba-Ughelli Expressway'],
    paymentPlans: ['Initial Deposit: ₦1,000,000', 'Balance within 3 months', 'Flexible Payment Options'],
    media: ['/lovable-uploads/BIG_league_Heaven_1.jpg', '/lovable-uploads/Homeslider2.png']
  },
  {
    id: 'big-league-haven-2',
    name: 'The Big League Haven 2',
    title: 'The Big League Haven 2 - Premium Estate',
    location: 'Off Warri-Asaba Road, Olor Ogwashi, Asaba, Delta State',
    price: '₦1,800,000',
    actualPrice: 2500000,
    prelaunchPrice: 1800000,
    imageUrl: '/lovable-uploads/Homeslider2.png',
    propertyType: 'Residential Land',
    property_category: 'land',
    size: 464,
    sqm: 464,
    totalPlots: 200,
    availablePlots: 185,
    pricePerPlot: 1800000,
    description: 'THE BIG LEAGUE HAVEN 2 – a prestigious estate located Off Warri-Asaba Road, Olor Ogwashi, Asaba, Delta State. Your golden opportunity to secure prime land in a fast-developing area with top-notch proposed estate features. Plot Size: 50ft x 100ft (464SQM), Freehold title.',
    features: ['Secure Perimeter Fencing', 'Good Road Network', 'Constant Power Supply', 'Portable Water System', 'Recreational & Green Areas'],
    amenities: ['Delta State Polytechnic Nearby', 'Admiralty University Access', 'Asaba International Airport', 'Asaba-Ughelli Expressway'],
    paymentPlans: ['Initial Deposit: ₦200,000', 'Balance within 3 months', 'Flexible Payment Options'],
    media: ['/lovable-uploads/Homeslider2.png']
  },
  // Hampton Ville Estate - New Addition  
  {
    id: 'hampton-ville-estate',
    name: 'Hampton Ville Estate',
    title: 'Hampton Ville Estate - Epe, Lagos',
    location: 'Epe - Ikorodu Road, Itoikin, Epe, Lagos',
    price: '₦9,900,000',
    actualPrice: 15000000,
    prelaunchPrice: 9900000,
    imageUrl: '/lovable-uploads/Hampton_Ville_-_Epe.jpg',
    propertyType: 'Residential Land',
    property_category: 'land',
    size: 500,
    sqm: 500,
    totalPlots: 200,
    availablePlots: 180,
    pricePerPlot: 9900000,
    description: 'Hampton Ville Estate – Free Documentation. Located at Epe - Ikorodu Road, Itoikin, Epe, Lagos. Plot Size: 50 x 100 SQF (500SQM), Gazette land title with excellent proposed estate features.',
    features: ['Gated Estate', 'Electricity & Streetlights', 'Well-Paved Roads & Drainage', 'Recreational Parks & Green Areas', 'Modern Security Gatehouse & 24/7 Security'],
    amenities: ['Close to Lagos Mainland', 'Good Road Network', 'Educational Institutions Nearby', 'Commercial Centers'],
    paymentPlans: ['Initial Deposit: ₦1,000,000', 'Balance within 3 months', 'Flexible Payment Plan'],
    media: ['/lovable-uploads/Hampton_Ville_-_Epe.jpg', '/lovable-uploads/Homeslider3.png']
  },
  {
    id: 'hampton-court-agbara',
    name: 'Hampton Court, Agbara',
    title: 'Hampton Court, Agbara - Luxury Living',
    location: 'Omilende Community, via Edu Town, Agbara, Ogun State',
    price: '₦950,000',
    actualPrice: 1500000,
    prelaunchPrice: 950000,
    imageUrl: '/lovable-uploads/Homeslider3.png',
    propertyType: 'Residential Land',
    property_category: 'land',
    size: 500,
    sqm: 500,
    totalPlots: 150,
    availablePlots: 142,
    pricePerPlot: 950000,
    description: 'Hampton Court, Agbara – an exclusive residential estate strategically located at Omilende Community, via Edu Town, Agbara, Ogun State. This estate combines serenity, accessibility, and class, making it the perfect destination for homeowners and investors.',
    features: ['Standard Perimeter Fencing', 'Electricity & Streetlights', 'Well-Paved Roads & Drainage', 'Recreational Parks & Green Areas', 'Modern Security Gatehouse & 24/7 Security'],
    amenities: ['Greenfield County Estate', 'Nestlé Nigeria Plc Factory', 'Agbara Industrial Estate', 'Crawford University', 'Crown Hotel & Resort'],
    paymentPlans: ['Initial Deposit: ₦200,000', 'Balance within 3 months', 'Flexible Payment Plan'],
    media: ['/lovable-uploads/Homeslider3.png']
  },
  // Luxury Home Sales - Featured homes
  {
    id: 'luxury-3bedroom-lagos',
    name: 'Premium 3-Bedroom House Lagos',
    title: 'Luxury 3-Bedroom House in Victoria Island',
    location: 'Victoria Island, Lagos',
    price: '₦180,000,000',
    imageUrl: luxury3BedroomLagos,
    propertyType: 'Residential House',
    property_category: 'home',
    size: 250,
    sqm: 250,
    totalPlots: 1,
    availablePlots: 1,
    pricePerPlot: 180000000,
    bedrooms: 3,
    bathrooms: 3,
    is_for_sale: true,
    is_for_rent: false,
    description: 'Stunning 3-bedroom house in the heart of Victoria Island. Features modern finishes, spacious living areas, fitted kitchen, and excellent security. Perfect for both purchase and rental.',
    features: ['3 Bedrooms', '3 Bathrooms', 'Modern Kitchen', 'Security System', 'Parking Space'],
    amenities: ['Swimming Pool', 'Gym', 'Garden', '24/7 Security', 'Generator'],
    paymentPlans: ['Outright Payment', 'Mortgage Available', '12 Months Plan'],
    media: [luxury3BedroomLagos]
  },
  {
    id: 'luxury-4bedroom-asaba',
    name: 'Luxury 4-Bedroom Duplex Asaba',
    title: 'Premium 4-Bedroom Duplex in Asaba',
    location: 'GRA, Asaba, Delta State',
    price: '₦95,000,000',
    imageUrl: luxury4BedroomAsaba,
    propertyType: 'Residential House',
    property_category: 'home',
    size: 320,
    sqm: 320,
    totalPlots: 1,
    availablePlots: 1,
    pricePerPlot: 95000000,
    bedrooms: 4,
    bathrooms: 4,
    is_for_sale: true,
    is_for_rent: false,
    description: 'Magnificent 4-bedroom duplex in the prestigious GRA of Asaba. Features exquisite interior finishing, modern kitchen, spacious compound, and BQ.',
    features: ['4 Bedrooms', '4 Bathrooms', 'BQ', 'Modern Kitchen', 'Spacious Compound'],
    amenities: ['Generator', 'Borehole', 'Security Post', 'Car Park', 'Garden'],
    paymentPlans: ['Outright Payment', 'Mortgage Available', '12 Months Plan'],
    media: [luxury4BedroomAsaba]
  },
  // Apartment Rentals - Featured rental
  {
    id: 'luxury-rental-ogun',
    name: 'Luxury Rental Apartment Ogun',
    title: 'Premium 2-Bedroom Apartment for Rent',
    location: 'Arepo, Ogun State',
    price: '₦2,500,000/year',
    monthlyRent: 250000,
    annualRent: 2500000,
    imageUrl: luxuryRentalOgun,
    propertyType: 'Apartment Rental',
    property_category: 'rental',
    size: 120,
    sqm: 120,
    totalPlots: 1,
    availablePlots: 1,
    pricePerPlot: 2500000,
    bedrooms: 2,
    bathrooms: 2,
    is_for_sale: false,
    is_for_rent: true,
    description: 'Stunning 2-bedroom apartment available for rent in Arepo. Fully furnished with modern appliances, in a secure estate with excellent amenities.',
    features: ['2 Bedrooms', '2 Bathrooms', 'Fully Furnished', 'Modern Kitchen', 'Balcony'],
    amenities: ['Swimming Pool', 'Gym', 'Security', '24/7 Power', 'Parking'],
    paymentPlans: ['Monthly: ₦250,000', 'Quarterly: ₦700,000', 'Annual: ₦2,500,000'],
    media: [luxuryRentalOgun]
  },
  // Land Estates
  {
    id: 'golden-haven',
    name: 'Golden Haven Estate',
    title: 'Golden Haven Estate',
    location: 'Ibeju-Lekki, Lagos',
    price: '₦3,000,000',
    imageUrl: '/lovable-uploads/Golden.png',
    propertyType: 'Residential',
    size: 600,
    sqm: 600,
    totalPlots: 120,
    availablePlots: 75,
    pricePerPlot: 3000000,
    description: 'A serene residential estate in the heart of Ibeju-Lekki, offering a blend of luxury and comfort.',
    features: ['Perimeter Fencing', 'Gatehouse', 'Good Road Network', 'Drainage System'],
    amenities: ['Recreational Park', 'Street Lights', 'Green Areas', 'Security Patrol'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
  {
    id: 'royal-city',
    name: 'Royal City Estate',
    title: 'Royal City Estate',
    location: 'Epe, Lagos',
    price: '₦2,000,000',
    imageUrl: '/lovable-uploads/Royalcity.png',
    propertyType: 'Residential',
    size: 500,
    sqm: 500,
    totalPlots: 150,
    availablePlots: 60,
    pricePerPlot: 2000000,
    description: 'An exquisite residential estate in Epe, designed for those who appreciate elegance and tranquility.',
    features: ['24/7 Security', 'Good Road Network', 'Electricity', 'Water Supply'],
    amenities: ['School', 'Hospital', 'Shopping Mall', 'Recreational Center'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan']
  },
  {
    id: 'diamond-resort',
    name: 'Diamond Resort Estate',
    title: 'Diamond Resort Estate',
    location: 'Owerri, Imo State',
    price: '₦2,800,000',
    imageUrl: '/lovable-uploads/Diamond.png',
    propertyType: 'Commercial',
    size: 700,
    sqm: 700,
    totalPlots: 80,
    availablePlots: 30,
    pricePerPlot: 2800000,
    description: 'A premium commercial estate in Owerri, ideal for businesses seeking a strategic location.',
    features: ['Ample Parking Space', 'Perimeter Fencing', 'Centralized Security', 'Backup Generator'],
    amenities: ['Conference Center', 'Business Lounge', 'High-Speed Internet', 'Restaurant'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
  {
    id: 'emerald-island',
    name: 'Emerald Island Estate',
    title: 'Emerald Island Estate',
    location: 'Port Harcourt, Rivers State',
    price: '₦3,200,000',
    imageUrl: '/lovable-uploads/Emerald.png',
    propertyType: 'Residential',
    size: 550,
    sqm: 550,
    totalPlots: 100,
    availablePlots: 40,
    pricePerPlot: 3200000,
    description: 'A luxurious residential estate in Port Harcourt, offering a serene and upscale living environment.',
    features: ['Gated Community', 'Landscaping', 'Street Lights', 'Waste Management'],
    amenities: ['Swimming Pool', 'Gym', 'Clubhouse', 'Children\'s Play Area'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan']
  },
  {
    id: 'the-boulevard',
    name: 'The Boulevard Estate',
    title: 'The Boulevard Estate',
    location: 'Abuja, FCT',
    price: '₦3,500,000',
    imageUrl: '/lovable-uploads/Boulevard.png',
    propertyType: 'Commercial',
    size: 800,
    sqm: 800,
    totalPlots: 60,
    availablePlots: 20,
    pricePerPlot: 3500000,
    description: 'A prestigious commercial estate in Abuja, perfect for establishing a strong business presence.',
    features: ['Excellent Road Network', '24/7 Power Supply', 'High Security', 'Modern Infrastructure'],
    amenities: ['Banking Facilities', 'Shopping Complex', 'Food Court', 'Office Spaces'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
  {
    id: 'precious-gardens',
    name: 'Precious Gardens Estate',
    title: 'Precious Gardens Estate',
    location: 'Sagamu, Ogun State',
    price: '₦2,500,000',
    imageUrl: '/lovable-uploads/Precious.png',
    propertyType: 'Residential',
    property_category: 'land',
    size: 500,
    sqm: 500,
    totalPlots: 100,
    availablePlots: 0, // SOLD OUT
    pricePerPlot: 2500000,
    description: 'A premium residential estate in Sagamu with modern amenities and excellent infrastructure.',
    features: ['24/7 Security', 'Good Road Network', 'Electricity', 'Water Supply'],
    amenities: ['Swimming Pool', 'Playground', 'Shopping Mall', 'Hospital'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan'],
    media: ['/lovable-uploads/Precious.png']
  },
  // Precious Gardens Scheme 2 - New Addition
  {
    id: 'precious-gardens-scheme-2',
    name: 'Precious Gardens Scheme 2',
    title: 'Precious Gardens Scheme 2',
    location: 'Ode-Omi, via Ibeju-Lekki, Lagos',
    price: '₦1,500,000',
    actualPrice: 2500000,
    prelaunchPrice: 1500000,
    imageUrl: '/lovable-uploads/PRECIOUS_GARDEN_SCHEME_2.jpg',
    propertyType: 'Residential Land',
    property_category: 'land',
    size: 500,
    sqm: 500,
    totalPlots: 200,
    availablePlots: 150,
    pricePerPlot: 1500000,
    description: 'Precious Gardens Scheme 2 - Provisional Survey Plan & Deed of Assignment. Located at Ode-Omi, via Ibeju-Lekki, Lagos. Plot Size: 500SQM (50ft by 100ft), 250SQM at ₦1.25M discounted price.',
    features: ['Gated Estate', 'Electricity & Streetlights', 'Well-Paved Roads & Drainage', 'Recreational Parks & Green Areas', 'Modern Security'],
    amenities: ['Close to Lekki-Epe Expressway', 'Commercial Areas', 'Educational Institutions', 'Healthcare Facilities'],
    paymentPlans: ['Initial Deposit: ₦500,000', 'Balance within 3 months', '6 Months Plan'],
    media: ['/lovable-uploads/PRECIOUS_GARDEN_SCHEME_2.jpg', '/lovable-uploads/Precious.png']
  },
  {
    id: 'sunflower-city',
    name: 'Sunflower City Estate',
    title: 'Sunflower City Estate',
    location: 'Benin, Edo State',
    price: '₦1,800,000',
    imageUrl: '/lovable-uploads/Sunflower.png',
    propertyType: 'Residential',
    size: 450,
    sqm: 450,
    totalPlots: 200,
    availablePlots: 120,
    pricePerPlot: 1800000,
    description: 'A vibrant residential estate in Benin, offering affordable and comfortable living spaces.',
    features: ['Well-Planned Layout', 'Green Spaces', 'Recreational Facilities', 'Security'],
    amenities: ['School', 'Market', 'Clinic', 'Community Center'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan']
  },
  {
    id: 'harmony-villas',
    name: 'Harmony Villas Estate',
    title: 'Harmony Villas Estate',
    location: 'Kano, Kano State',
    price: '₦2,200,000',
    imageUrl: '/lovable-uploads/Harmony.png',
    propertyType: 'Residential',
    size: 500,
    sqm: 500,
    totalPlots: 90,
    availablePlots: 50,
    pricePerPlot: 2200000,
    description: 'A peaceful residential estate in Kano, designed for family living with essential amenities.',
    features: ['Perimeter Fence', 'Gatehouse', 'Good Road Network', 'Drainage System'],
    amenities: ['Park', 'Street Lights', 'Water Supply', 'Security Patrol'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
  {
    id: 'grand-view',
    name: 'Grand View Estate',
    title: 'Grand View Estate',
    location: 'Enugu, Enugu State',
    price: '₦2,700,000',
    imageUrl: '/lovable-uploads/Grandview.png',
    propertyType: 'Residential',
    size: 550,
    sqm: 550,
    totalPlots: 110,
    availablePlots: 65,
    pricePerPlot: 2700000,
    description: 'A scenic residential estate in Enugu, offering beautiful views and a comfortable lifestyle.',
    features: ['24/7 Security', 'Good Road Network', 'Electricity', 'Water Supply'],
    amenities: ['School', 'Hospital', 'Shopping Mall', 'Recreational Center'],
    paymentPlans: ['Outright Payment', '6 Months Plan', '12 Months Plan']
  },
  {
    id: 'city-lights',
    name: 'City Lights Estate',
    title: 'City Lights Estate',
    location: 'Kaduna, Kaduna State',
    price: '₦2,900,000',
    imageUrl: '/lovable-uploads/Citylight.png',
    propertyType: 'Commercial',
    size: 650,
    sqm: 650,
    totalPlots: 70,
    availablePlots: 25,
    pricePerPlot: 2900000,
    description: 'A modern commercial estate in Kaduna, ideal for businesses looking for a prime location.',
    features: ['Ample Parking Space', 'Perimeter Fencing', 'Centralized Security', 'Backup Generator'],
    amenities: ['Conference Center', 'Business Lounge', 'High-Speed Internet', 'Restaurant'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan']
  },
  // Greenfield County Estate - New Addition
  {
    id: 'greenfield-county-estate',
    name: 'Greenfield County Estate',
    title: 'Greenfield County Estate & Farmland',
    location: 'Agbara, Ogun State',
    price: '₦2,500,000',
    actualPrice: 3200000,
    prelaunchPrice: 2500000,
    imageUrl: '/lovable-uploads/GREENFIELD.jpg',
    propertyType: 'Residential Land',
    property_category: 'land',
    size: 500,
    sqm: 500,
    totalPlots: 300,
    availablePlots: 250,
    pricePerPlot: 2500000,
    description: 'Introducing Greenfield County Estate & Farmland located at Agbara, Ogun State. Survey Plan & Deed of Assignment with 500SQM plot. Discounted Price ₦2.5M, Actual Price: ₦3.2M. Documentation Inclusive.',
    features: ['Gated Estate', 'Street Light', '24/7 Security', 'Good Roads', 'Shopping Mall', 'Recreational Park', 'Electricity', 'Gymnasium'],
    amenities: ['Crawford University', 'Badagry Expressway', 'Edu Community School', 'Crown Hotel & Resort', 'Nestle PLC Agbara', 'Lagos State Univ. of Education'],
    paymentPlans: ['Outright Payment', '3 Months Plan', '6 Months Plan'],
    media: ['/lovable-uploads/GREENFIELD.jpg']
  },
  // The Ambassadors Estate - New Addition
  {
    id: 'ambassadors-estate',
    name: 'The Ambassadors Estate',
    title: 'The Ambassadors Estate',
    location: 'Ode-Omi Community, via Ibeju-Lekki, Lagos',
    price: '₦1,800,000',
    actualPrice: 2500000,
    prelaunchPrice: 1800000,
    imageUrl: '/lovable-uploads/The_Ambassadors_Estate.jpg',
    propertyType: 'Residential Land',
    property_category: 'land',
    size: 500,
    sqm: 500,
    totalPlots: 200,
    availablePlots: 170,
    pricePerPlot: 1800000,
    description: 'The Ambassadors Estate located at Ode-Omi Community, via Ibeju-Lekki, Lagos. Discounted Price ₦1.8M, Actual Price: ₦2.5M. Land Title: Freehold, Plot Size: 50 x 100 SQF (500SQM). Initial Deposit: ₦1M, Balance payable in 3 Months.',
    features: ['Secure Perimeter Fencing', 'Good Road Network', 'Constant Power Supply', 'Portable Water System', 'Recreational & Green Areas'],
    amenities: ['Close to Lekki-Epe Expressway', 'Commercial Areas', 'Educational Institutions', 'Healthcare Facilities'],
    paymentPlans: ['Initial Deposit: ₦1,000,000', 'Balance within 3 months', 'Flexible Payment Options'],
    media: ['/lovable-uploads/The_Ambassadors_Estate.jpg', '/lovable-uploads/The Ambassadors.jpg']
  },
  // Bridgefort Biz Hub - New Addition
  {
    id: 'bridgefort-biz-hub',
    name: 'Bridgefort Biz Hub',
    title: 'Bridgefort Biz Hub - Commercial Estate',
    location: 'Ebute Okun, Ode-Omi, via Ibeju-Lekki',
    price: '₦2,500,000',
    actualPrice: 3000000,
    prelaunchPrice: 2500000,
    imageUrl: '/lovable-uploads/Bridgefort_Biz_Hub_-_Ode_Omi.jpg',
    propertyType: 'Commercial Land',
    property_category: 'land',
    size: 500,
    sqm: 500,
    totalPlots: 150,
    availablePlots: 120,
    pricePerPlot: 2500000,
    description: 'Bridgefort Biz Hub - Commercial Estate located at Ebute Okun, Ode-Omi, via Ibeju-Lekki. Discounted Price ₦2.5M, Actual Price: ₦3M. Land Title: Freehold, Plot Size: 50 x 100 SQF (500SQM). Initial Deposit: ₦1M, Balance payable in 3 Months.',
    features: ['Gated Estate', 'Electricity & Streetlights', 'Well-Paved Roads & Drainage', 'Shopping Mall', 'Business Lounge', 'High-Speed Internet', 'Restaurant'],
    amenities: ['Strategic Commercial Location', 'Close to Major Roads', 'Business Districts', 'Banking Facilities'],
    paymentPlans: ['Initial Deposit: ₦1,000,000', 'Balance within 3 months', 'Flexible Payment Options'],
    media: ['/lovable-uploads/Bridgefort_Biz_Hub_-_Ode_Omi.jpg']
  },
];
