project_id = "xyvspvtdaacqfmfocvhw"

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false

[functions.generate-blog-article]
verify_jwt = false

[functions.send-training-reminder]
verify_jwt = false

[functions.generate-certificate]
verify_jwt = false

[functions.send-certificate-email]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false

[functions.send-lockout-notification]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.verify-otp-reset-password]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.resend-receive-emails]
verify_jwt = false
