import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { toast } from 'sonner';
import { format } from 'date-fns';
import { useEmail } from '@/hooks/useEmail';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/auth';
import AdminEmailTemplates from './AdminEmailTemplates';
import AdminBulkEmail from './AdminBulkEmail';
import GmailSidebar, { EmailFolder } from './email/GmailSidebar';
import EmailListItem, { UnifiedEmail } from './email/EmailListItem';
import EmailReadingPane from './email/EmailReadingPane';
import ComposeDialog from './email/ComposeDialog';
import EmailLoginScreen, { AvailableMailbox } from './email/EmailLoginScreen';
import AdminEmailSettings from './AdminEmailSettings';
import { Mail, Search, RefreshCw, Trash2, Archive, CheckSquare, Star, User, Inbox, GripVertical, Plus, Filter, SlidersHorizontal, ChevronDown, PanelLeft, Clock3, ShieldCheck, Send, Sparkles, MoreHorizontal, X } from 'lucide-react';

type EmailAccount = 'resend' | 'gmail';
const ACTIVE_MAILBOX_KEY = 'admin_email_active_mailbox';

export default function AdminEmailCenter() {
  const { user, hasMailboxAccess, hasPermission } = useAuth();
  const { sentEmails, inboxMessages, contacts, loading, sending, sendEmail, replyToMessage, deleteEmailLog, deleteMessage, refreshAll } = useEmail();
  const [activeFolder, setActiveFolder] = useState<EmailFolder>('inbox');
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedEmailId, setSelectedEmailId] = useState<string | null>(null);
  const [checkedIds, setCheckedIds] = useState<Set<string>>(new Set());
  const [composeOpen, setComposeOpen] = useState(false);
  const [composeInitial, setComposeInitial] = useState({ to: '', name: '', subject: '', body: '' });
  const [fullViewEmail, setFullViewEmail] = useState(false);
  const [listWidth, setListWidth] = useState(430);
  const [isResizing, setIsResizing] = useState(false);
  const [adminEmails, setAdminEmails] = useState<any[]>([]);
  const [availableMailboxes, setAvailableMailboxes] = useState<AvailableMailbox[]>([]);
  const [mailboxesLoading, setMailboxesLoading] = useState(true);
  const [activeMailbox, setActiveMailbox] = useState<string | null>(null);
  const [showEmailLogin, setShowEmailLogin] = useState(true);
  const [connectingEmail, setConnectingEmail] = useState<string | null>(null);
  const [disconnectingEmail, setDisconnectingEmail] = useState<string | null>(null);
  const [syncingGmail, setSyncingGmail] = useState(false);
  const [mobileSidebar, setMobileSidebar] = useState(false);
  const [showFilters, setShowFilters] = useState(false);
  const [unreadOnly, setUnreadOnly] = useState(false);
  const [searchParams, setSearchParams] = useSearchParams();

  const activeAccount: EmailAccount = useMemo(() => availableMailboxes.find(m => m.mailbox_email === activeMailbox)?.mailbox_provider === 'gmail' ? 'gmail' : 'resend', [availableMailboxes, activeMailbox]);
  const fetchAllAdminEmails = useCallback(async () => { const { data } = await supabase.from('admin_emails').select('*').order('created_at', { ascending: false }); if (data) setAdminEmails(data); }, []);
  const fetchAvailableMailboxes = useCallback(async () => {
    if (!user) return; setMailboxesLoading(true);
    const { data } = await supabase.rpc('get_available_mailboxes', { _user_id: user.id });
    if (data) {
      const mailboxes = data as AvailableMailbox[]; setAvailableMailboxes(mailboxes);
      const saved = localStorage.getItem(ACTIVE_MAILBOX_KEY);
      if (saved && mailboxes.some(m => m.mailbox_email === saved)) { setActiveMailbox(saved); setShowEmailLogin(false); }
      else { setActiveMailbox(null); setShowEmailLogin(true); if (saved) localStorage.removeItem(ACTIVE_MAILBOX_KEY); }
    }
    setMailboxesLoading(false);
  }, [user]);
  const selectMailbox = useCallback((mailboxEmail: string) => { setActiveMailbox(mailboxEmail); localStorage.setItem(ACTIVE_MAILBOX_KEY, mailboxEmail); setShowEmailLogin(false); setSelectedEmailId(null); setCheckedIds(new Set()); setSearchTerm(''); }, []);
  const connectGmail = async (mailboxEmail: string) => {
    const allowed = await hasMailboxAccess(mailboxEmail, 'gmail'); if (!allowed && !hasPermission('admin:all')) { toast.error('You do not have permission to connect this mailbox.'); return; }
    setConnectingEmail(mailboxEmail); try { const { data, error } = await supabase.functions.invoke('gmail-oauth-start'); if (error || !data?.url) throw new Error(error?.message || 'Could not start Gmail connection'); window.location.href = data.url; } catch (e: any) { toast.error(e.message || 'Could not start Gmail connection'); setConnectingEmail(null); }
  };
  const disconnectGmail = async (mailboxEmail: string) => {
    setDisconnectingEmail(mailboxEmail); try { const { error } = await supabase.functions.invoke('gmail-oauth-disconnect', { body: { mailboxEmail } }); if (error) throw error; toast.success(`Signed out of ${mailboxEmail}`); if (activeMailbox === mailboxEmail) { setActiveMailbox(null); localStorage.removeItem(ACTIVE_MAILBOX_KEY); setShowEmailLogin(true); } fetchAvailableMailboxes(); } catch (e: any) { toast.error(e.message || 'Could not disconnect this account'); } finally { setDisconnectingEmail(null); }
  };
  const syncGmailNow = async (mailboxEmail: string) => {
    const allowed = await hasMailboxAccess(mailboxEmail, 'gmail'); if (!allowed && !hasPermission('admin:all')) { toast.error('You do not have permission to sync this mailbox.'); return; }
    setSyncingGmail(true); try { const { data, error } = await supabase.functions.invoke('gmail-sync-to-db', { body: { maxPerLabel: 25, mailboxEmail } }); if (error) throw error; if (data?.scopeRestricted) toast.error('Gmail has limited access. Reconnect for full mail sync.'); else toast.success(`Synced ${data?.synced ?? 0} Gmail messages`); fetchAllAdminEmails(); } catch (e: any) { toast.error(e.message || 'Gmail sync failed'); } finally { setSyncingGmail(false); }
  };
  useEffect(() => {
    fetchAvailableMailboxes(); const connected = searchParams.get('gmail_connected'); const connectedEmail = searchParams.get('gmail_email'); const gmailError = searchParams.get('gmail_error');
    if (connected && connectedEmail) { toast.success(`Gmail connected: ${connectedEmail}`); selectMailbox(connectedEmail); fetchAvailableMailboxes(); syncGmailNow(connectedEmail); }
    else if (gmailError) { const attemptedEmail = searchParams.get('gmail_attempted_email'); const messages: Record<string, string> = { missing_code_or_state: 'Gmail connection was cancelled or incomplete.', invalid_or_expired_state: 'That connection link expired — try connecting again.', expired_state: 'That connection link expired — try connecting again.', token_exchange_failed: 'Google rejected the connection request. Try again.', profile_fetch_failed: 'Connected, but could not read the Gmail account details.', mailbox_not_authorized: attemptedEmail ? `You signed into ${attemptedEmail} on Google, but you are not authorized for that mailbox.` : 'You are not authorized for that Gmail account.', no_refresh_token: 'Google did not grant lasting access. Reconnect Gmail after checking your Google Account security settings.', storage_failed: 'Connected, but saving the connection failed. Try again.', unexpected_error: 'Something went wrong connecting Gmail. Try again.' }; toast.error(messages[gmailError] || `Gmail connection failed: ${gmailError}`); }
    if (connected || gmailError) { ['gmail_connected', 'gmail_email', 'gmail_error', 'gmail_attempted_email'].forEach(k => searchParams.delete(k)); setSearchParams(searchParams, { replace: true }); }
    refreshAll(); fetchAllAdminEmails(); const ch = supabase.channel('admin-emails-gmail').on('postgres_changes', { event: '*', schema: 'public', table: 'admin_emails' }, fetchAllAdminEmails).subscribe(); return () => { supabase.removeChannel(ch); };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  const handleMouseDown = useCallback((e: React.MouseEvent) => { e.preventDefault(); setIsResizing(true); const startX = e.clientX; const startWidth = listWidth; const move = (ev: MouseEvent) => setListWidth(Math.max(300, Math.min(650, startWidth + ev.clientX - startX))); const up = () => { setIsResizing(false); document.removeEventListener('mousemove', move); document.removeEventListener('mouseup', up); }; document.addEventListener('mousemove', move); document.addEventListener('mouseup', up); }, [listWidth]);
  const allUnifiedEmails: UnifiedEmail[] = useMemo(() => {
    const fromAdminEmails = adminEmails.map(e => ({ id: e.id, from_email: e.from_email, from_name: e.from_name || '', to_email: e.to_email, to_name: e.to_name || '', subject: e.subject || '', body: e.body || '', html: e.html || undefined, created_at: e.created_at, is_read: e.is_read, is_starred: e.is_starred, folder: e.folder, source: e.source, has_attachments: Array.isArray(e.attachments) && e.attachments.length > 0, _original: e }));
    const fromContactMessages = inboxMessages.map(m => ({ id: `cm-${m.id}`, from_email: m.email, from_name: m.name, to_email: 'admin@pwanbridgefort.ng', to_name: 'Admin', subject: m.subject, body: m.message, created_at: m.created_at, is_read: m.responded, is_starred: false, folder: 'inbox', source: 'contact_form', _original: m }));
    const fromEmailLogs = sentEmails.map(e => ({ id: `log-${e.id}`, from_email: 'noreply@bridgeforthomes.com', from_name: 'Bridgefort Homes Development Ltd', to_email: e.recipient_email, to_name: e.recipient_name || '', subject: e.subject, body: e.body, created_at: e.sent_at, is_read: true, is_starred: false, folder: 'sent', source: 'email_log', _original: e }));
    return [...fromAdminEmails, ...fromContactMessages, ...fromEmailLogs];
  }, [adminEmails, inboxMessages, sentEmails]);
  const deduped = useMemo(() => { const seen = new Map<string, UnifiedEmail>(); [...allUnifiedEmails].sort((a,b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()).forEach(e => { const key = `${e.from_email}|${e.subject}|${e.to_email}`; const existing = [...seen.values()].find(x => `${x.from_email}|${x.subject}|${x.to_email}` === key); if (existing && Math.abs(new Date(existing.created_at).getTime() - new Date(e.created_at).getTime()) < 5000) return; seen.set(`${key}|${e.id}`, e); }); return [...seen.values()]; }, [allUnifiedEmails]);
  const getThreadId = (subject: string) => subject.replace(/^(re|fwd|fw):\s*/gi, '').trim().toLowerCase();
  const accountEmails = useMemo(() => activeMailbox ? deduped.filter(e => e.to_email === activeMailbox || e.from_email === activeMailbox) : [], [deduped, activeMailbox]);
  const folderEmails = useMemo(() => { let filtered = accountEmails; switch (activeFolder) { case 'inbox': filtered = filtered.filter(e => e.folder === 'inbox'); break; case 'sent': filtered = filtered.filter(e => e.folder === 'sent'); break; case 'drafts': filtered = filtered.filter(e => e.folder === 'drafts'); break; case 'starred': filtered = filtered.filter(e => e.is_starred); break; case 'spam': filtered = filtered.filter(e => e.folder === 'spam'); break; case 'archive': filtered = filtered.filter(e => e.folder === 'archive'); break; case 'trash': filtered = filtered.filter(e => e.folder === 'trash'); break; default: filtered = []; } if (unreadOnly) filtered = filtered.filter(e => !e.is_read); if (searchTerm.trim()) { const s = searchTerm.toLowerCase(); filtered = filtered.filter(e => [e.subject,e.from_email,e.from_name,e.to_email,e.body].some(v => v?.toLowerCase().includes(s))); } return [...filtered].sort((a,b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()); }, [accountEmails, activeFolder, searchTerm, unreadOnly]);
  const selectedEmail = folderEmails.find(e => e.id === selectedEmailId) || null;
  const threadEmails = useMemo(() => { if (!selectedEmail) return []; const tid = getThreadId(selectedEmail.subject); return deduped.filter(e => getThreadId(e.subject) === tid && (e.from_email === selectedEmail.from_email || e.to_email === selectedEmail.from_email || e.from_email === selectedEmail.to_email)).sort((a,b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime()); }, [selectedEmail,deduped]);
  const counts = useMemo(() => ({ inbox: accountEmails.filter(e => e.folder === 'inbox').length, unread: accountEmails.filter(e => e.folder === 'inbox' && !e.is_read).length, starred: accountEmails.filter(e => e.is_starred).length, sent: accountEmails.filter(e => e.folder === 'sent').length, drafts: accountEmails.filter(e => e.folder === 'drafts').length, spam: accountEmails.filter(e => e.folder === 'spam').length, archive: accountEmails.filter(e => e.folder === 'archive').length, trash: accountEmails.filter(e => e.folder === 'trash').length, contacts: contacts.length }), [accountEmails,contacts]);
  const toggleStar = async (email: UnifiedEmail) => { if (email.id.startsWith('cm-') || email.id.startsWith('log-') || email.id.startsWith('resend-')) { toast.info('Star is available for admin emails'); return; } await supabase.from('admin_emails').update({ is_starred: !email.is_starred }).eq('id', email.id); fetchAllAdminEmails(); };
  const moveToFolder = async (email: UnifiedEmail, folder: string) => { if (email.id.startsWith('cm-')) { if (folder === 'trash') { await deleteMessage(email._original.id); toast.success('Message deleted'); } return; } if (email.id.startsWith('log-')) { if (folder === 'trash') { await deleteEmailLog(email._original.id); toast.success('Email log deleted'); } return; } if (email.id.startsWith('resend-')) { toast.info('Cannot move this message'); return; } await supabase.from('admin_emails').update({ folder }).eq('id', email.id); toast.success(`Moved to ${folder}`); fetchAllAdminEmails(); if (selectedEmailId === email.id) setSelectedEmailId(null); };
  const handleBulkMove = async (folder: 'archive'|'trash') => { const ids = [...checkedIds].filter(id => !id.startsWith('cm-') && !id.startsWith('log-') && !id.startsWith('resend-')); if (!ids.length) { toast.info('Select emails you can manage first'); return; } const { error } = await supabase.from('admin_emails').update({ folder }).in('id', ids); if (error) toast.error(error.message); else toast.success(`${ids.length} email${ids.length === 1 ? '' : 's'} moved to ${folder}`); setCheckedIds(new Set()); fetchAllAdminEmails(); };
  const markRead = async (email: UnifiedEmail) => { if (email.id.startsWith('cm-') || email.id.startsWith('log-') || email.id.startsWith('resend-')) return; await supabase.from('admin_emails').update({ is_read: !email.is_read }).eq('id', email.id); fetchAllAdminEmails(); };
  const handleSelectEmail = (email: UnifiedEmail) => { setSelectedEmailId(email.id); if (!email.is_read && !email.id.startsWith('cm-') && !email.id.startsWith('log-')) supabase.from('admin_emails').update({ is_read: true }).eq('id', email.id).then(fetchAllAdminEmails); };
  const handleComposeSend = async (to: string, name: string, subj: string, body: string, cc?: string, bcc?: string) => {
    if (!to || !subj || !body) { toast.error('Fill in all required fields'); return { success: false, error: 'Missing fields' }; }
    if (!activeMailbox) { toast.error('No mailbox selected'); return { success: false, error: 'No mailbox selected' }; }
    let result: { success: boolean; error?: string };
    if (activeAccount === 'gmail') {
      const { error } = await supabase.functions.invoke('gmail-sync', { body: { action: 'send-message', mailboxEmail: activeMailbox, to, subject: subj, html: body, cc, bcc } });
      result = error ? { success: false, error: error.message } : { success: true };
    } else {
      result = await sendEmail(to, subj, body, name, activeMailbox, cc, bcc);
    }
    if (result.success) { toast.success('Email sent'); fetchAllAdminEmails(); } else toast.error(result.error || 'Failed to send');
    return result;
  };
  const handleSaveDraft = async (to: string, name: string, subj: string, body: string) => { const { error } = await supabase.from('admin_emails').insert({ from_email: activeMailbox || 'noreply@bridgeforthomes.com', from_name: 'Bridgefort Homes Development Ltd', to_email: to || 'draft', to_name: name || null, subject: subj || '(No Subject)', body: body || '', folder: 'drafts', is_read: true, source: 'draft' }); if (error) toast.error(error.message); else { toast.success('Draft saved'); fetchAllAdminEmails(); } };
  const handleReply = async (email: UnifiedEmail, subj: string, body: string) => { if (email.id.startsWith('cm-')) { const result = await replyToMessage(email._original, subj, body); if (result.success) toast.success('Reply sent'); else toast.error(result.error || 'Failed'); return result; } return handleComposeSend(email.from_email, email.from_name, subj, body); };
  const handleForward = async (_email: UnifiedEmail, to: string, subj: string, body: string) => handleComposeSend(to, '', subj, body);
  const handleOpenDraft = (email: UnifiedEmail) => { setComposeInitial({ to: email.to_email === 'draft' ? '' : email.to_email, name: email.to_name || '', subject: email.subject, body: email.body }); setComposeOpen(true); if (!email.id.startsWith('cm-') && !email.id.startsWith('log-') && !email.id.startsWith('resend-')) supabase.from('admin_emails').delete().eq('id', email.id).then(fetchAllAdminEmails); };
  const handleRefresh = () => { refreshAll(); fetchAllAdminEmails(); if (activeAccount === 'gmail' && activeMailbox) syncGmailNow(activeMailbox); };
  const isToolView = ['contacts','templates','bulk'].includes(activeFolder);
  if (showEmailLogin || !activeMailbox) return <div className="min-h-[calc(100vh-8rem)] rounded-[28px] overflow-hidden border border-slate-200/80 bg-gradient-to-br from-slate-950 via-slate-900 to-slate-800 shadow-2xl"><div className="h-full p-4 md:p-6"><EmailLoginScreen mailboxes={availableMailboxes} loading={mailboxesLoading} activeMailbox={activeMailbox} connectingEmail={connectingEmail} disconnectingEmail={disconnectingEmail} onSelect={selectMailbox} onConnectGmail={connectGmail} onDisconnectGmail={disconnectGmail} /></div></div>;
  return <div className={`min-h-[calc(100vh-8rem)] rounded-[28px] overflow-hidden border border-slate-200/80 bg-slate-50 shadow-2xl ${isResizing ? 'select-none' : ''}`}><div className="flex h-full min-h-[calc(100vh-8rem)] flex-col">
    <header className="flex shrink-0 items-center gap-3 border-b border-slate-200 bg-white px-4 py-3 md:px-5"><Button variant="ghost" size="icon" className="md:hidden" onClick={() => setMobileSidebar(true)}><PanelLeft className="h-5 w-5" /></Button><div className="hidden sm:flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-900 text-white"><Mail className="h-5 w-5" /></div><div className="min-w-0"><div className="flex items-center gap-2"><h1 className="text-base font-semibold text-slate-900">Email Center</h1><Badge className="hidden sm:inline-flex rounded-full bg-emerald-50 text-emerald-700 hover:bg-emerald-50"><span className="mr-1.5 h-1.5 w-1.5 rounded-full bg-emerald-500" />Connected</Badge></div><p className="hidden text-xs text-slate-500 sm:block">Centralized communication workspace</p></div><div className="relative ml-2 flex min-w-0 flex-1 max-w-xl"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={searchTerm} onChange={e => setSearchTerm(e.target.value)} placeholder="Search mail, people and conversations..." className="h-10 rounded-xl border-slate-200 bg-slate-50 pl-10 pr-10 shadow-none" /><button onClick={() => setShowFilters(v => !v)} className={`absolute right-2 top-1/2 -translate-y-1/2 rounded-lg p-1.5 ${showFilters ? 'bg-slate-200 text-slate-900' : 'text-slate-400 hover:bg-slate-200'}`}><SlidersHorizontal className="h-4 w-4" /></button></div><div className="ml-auto flex items-center gap-2"><button onClick={() => setShowEmailLogin(true)} className="hidden max-w-[240px] items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-left hover:bg-slate-50 sm:flex"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-slate-100"><Mail className="h-3.5 w-3.5 text-slate-700" /></span><span className="min-w-0"><span className="block truncate text-xs font-semibold text-slate-800">{activeMailbox}</span><span className="block text-[10px] text-slate-500">Switch mailbox</span></span><ChevronDown className="h-3.5 w-3.5 text-slate-400" /></button>{activeAccount === 'gmail' && <Button size="sm" variant="outline" onClick={() => syncGmailNow(activeMailbox)} disabled={syncingGmail} className="hidden rounded-xl border-slate-200 md:flex"><RefreshCw className={`mr-1.5 h-3.5 w-3.5 ${syncingGmail ? 'animate-spin' : ''}`} />Sync</Button>}<Button variant="ghost" size="icon" onClick={handleRefresh} disabled={loading} className="rounded-xl"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} /></Button><AdminEmailSettings /><Button size="sm" onClick={() => { setComposeInitial({to:'',name:'',subject:'',body:''}); setComposeOpen(true); }} className="hidden rounded-xl bg-slate-900 px-4 text-white md:flex"><Plus className="mr-1.5 h-4 w-4" />Compose</Button></div></header>
    {showFilters && !isToolView && <div className="flex shrink-0 flex-wrap items-center gap-2 border-b border-slate-200 bg-white px-4 py-2.5"><span className="mr-1 text-xs font-medium text-slate-500"><Filter className="mr-1 inline h-3.5 w-3.5" />Filters</span><button onClick={() => setUnreadOnly(v => !v)} className={`rounded-full border px-3 py-1.5 text-xs font-medium ${unreadOnly ? 'border-slate-900 bg-slate-900 text-white' : 'border-slate-200 bg-white text-slate-600'}`}>Unread only</button><button onClick={() => {setSearchTerm('');setUnreadOnly(false);}} className="rounded-full px-3 py-1.5 text-xs text-slate-500">Clear filters</button></div>}
    <div className="relative flex min-h-0 flex-1 overflow-hidden"><aside className="hidden w-[230px] shrink-0 border-r border-slate-200 bg-white p-3 md:block"><GmailSidebar activeFolder={activeFolder} onFolderChange={f=>{setActiveFolder(f);setSelectedEmailId(null);setSearchTerm('');setFullViewEmail(false);}} onCompose={()=>{setComposeInitial({to:'',name:'',subject:'',body:''});setComposeOpen(true);}} counts={counts}/><div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-3"><div className="mb-2 flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-600"/><span className="text-xs font-semibold">Mailbox access</span></div><p className="truncate text-[11px] text-slate-500">{activeMailbox}</p><button onClick={()=>setShowEmailLogin(true)} className="mt-2 text-[11px] font-semibold">Manage accounts</button></div></aside>
    {mobileSidebar && <div className="absolute inset-0 z-50 md:hidden"><button className="absolute inset-0 bg-slate-950/40" onClick={()=>setMobileSidebar(false)}/><aside className="relative h-full w-[280px] bg-white p-4 shadow-2xl"><div className="mb-4 flex justify-end"><Button variant="ghost" size="icon" onClick={()=>setMobileSidebar(false)}><X className="h-5 w-5"/></Button></div><GmailSidebar activeFolder={activeFolder} onFolderChange={f=>{setActiveFolder(f);setSelectedEmailId(null);setMobileSidebar(false);}} onCompose={()=>{setComposeInitial({to:'',name:'',subject:'',body:''});setComposeOpen(true);setMobileSidebar(false);}} counts={counts}/></aside></div>}
    {!fullViewEmail && !isToolView && <section className={`${selectedEmailId?'hidden md:flex':'flex'} min-w-0 shrink-0 flex-col border-r border-slate-200 bg-white`} style={{width:selectedEmailId?listWidth:undefined,maxWidth:selectedEmailId?'58%':undefined,flex:selectedEmailId?'0 0 auto':'1 1 auto'}}><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div><div className="flex items-center gap-2"><h2 className="text-sm font-semibold capitalize">{activeFolder}</h2>{counts.unread>0&&<Badge className="rounded-full bg-slate-900 px-2 text-[10px] text-white">{counts.unread} new</Badge>}</div><p className="mt-0.5 text-[11px] text-slate-400">{folderEmails.length} conversation{folderEmails.length===1?'':'s'}</p></div><div className="flex items-center gap-1"><Button variant="ghost" size="icon" className="h-8 w-8" onClick={()=>{const all=new Set(folderEmails.map(e=>e.id));setCheckedIds(checkedIds.size===folderEmails.length?new Set():all);}}><CheckSquare className="h-4 w-4"/></Button><Button variant="ghost" size="icon" className="h-8 w-8" onClick={()=>setShowFilters(v=>!v)}><Filter className="h-4 w-4"/></Button><Button variant="ghost" size="icon" className="h-8 w-8"><MoreHorizontal className="h-4 w-4"/></Button></div></div>{checkedIds.size>0&&<div className="flex items-center gap-1 border-b border-slate-100 bg-slate-50 px-3 py-2"><span className="mr-auto text-xs font-medium">{checkedIds.size} selected</span><Button variant="ghost" size="sm" onClick={()=>handleBulkMove('archive')}><Archive className="mr-1.5 h-3.5 w-3.5"/>Archive</Button><Button variant="ghost" size="sm" className="text-red-600" onClick={()=>handleBulkMove('trash')}><Trash2 className="mr-1.5 h-3.5 w-3.5"/>Delete</Button></div>}<ScrollArea className="min-h-0 flex-1">{loading&&folderEmails.length===0?<div className="space-y-2 p-3">{Array.from({length:7}).map((_,i)=><div key={i} className="h-20 animate-pulse rounded-2xl bg-slate-100"/>)}</div>:folderEmails.length===0?<div className="flex h-full min-h-[360px] flex-col items-center justify-center px-8 text-center"><div className="mb-4 flex h-16 w-16 items-center justify-center rounded-3xl bg-slate-100"><Inbox className="h-7 w-7 text-slate-400"/></div><p className="text-sm font-semibold">Nothing here yet</p><p className="mt-1 max-w-xs text-xs leading-5 text-slate-400">Your {activeFolder} messages will appear here when they arrive.</p></div>:folderEmails.map(email=><EmailListItem key={email.id} email={email} isSelected={selectedEmailId===email.id} isChecked={checkedIds.has(email.id)} onSelect={()=>activeFolder==='drafts'?handleOpenDraft(email):handleSelectEmail(email)} onCheck={c=>setCheckedIds(prev=>{const next=new Set(prev);c?next.add(email.id):next.delete(email.id);return next;})} onStar={()=>toggleStar(email)}/>)}</ScrollArea></section>}
    {selectedEmailId&&!fullViewEmail&&!isToolView&&<div className="hidden w-1.5 shrink-0 cursor-col-resize items-center justify-center bg-white hover:bg-slate-50 md:flex" onMouseDown={handleMouseDown}><GripVertical className="h-4 w-4 text-slate-300"/></div>}
    {activeFolder==='contacts'&&<ScrollArea className="min-w-0 flex-1 bg-slate-50 p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Contacts</h2><p className="text-xs text-slate-500">Start conversations from your CRM contacts.</p></div><Badge variant="outline" className="rounded-full">{contacts.length}</Badge></div><div className="grid grid-cols-1 gap-3 lg:grid-cols-2 xl:grid-cols-3">{contacts.filter(c=>c.email).map(contact=><div key={contact.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-100"><User className="h-4 w-4"/></div><div className="min-w-0"><p className="truncate text-sm font-semibold">{contact.first_name||contact.last_name?`${contact.first_name||''} ${contact.last_name||''}`.trim():'No Name'}</p><p className="truncate text-xs text-slate-500">{contact.email}</p></div></div><Button variant="outline" size="sm" className="mt-3 w-full rounded-xl" onClick={()=>{setComposeInitial({to:contact.email||'',name:`${contact.first_name||''} ${contact.last_name||''}`.trim(),subject:'',body:''});setComposeOpen(true);}}><Mail className="mr-1.5 h-3.5 w-3.5"/>Email contact</Button></div>)}</div></ScrollArea>}
    {activeFolder==='templates'&&<ScrollArea className="min-w-0 flex-1 bg-slate-50 p-5"><AdminEmailTemplates onSelectTemplate={template=>{setComposeInitial({to:'',name:'',subject:template.subject,body:template.body});setComposeOpen(true);toast.success('Template loaded');}}/></ScrollArea>}
    {activeFolder==='bulk'&&<ScrollArea className="min-w-0 flex-1 bg-slate-50 p-5"><AdminBulkEmail/></ScrollArea>}
    {!isToolView&&<section className={`${selectedEmailId?'flex':'hidden md:flex'} min-w-0 flex-1 flex-col bg-white`}>{selectedEmail?<><div className="flex shrink-0 items-center justify-between border-b border-slate-100 bg-white px-4 py-2.5 md:px-6"><div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-slate-100"><Send className="h-3.5 w-3.5"/></span><span className="text-xs text-slate-500">Conversation</span><span className="text-xs text-slate-300">•</span><span className="truncate text-xs font-medium">{activeMailbox}</span></div><div className="flex items-center gap-1"><Button variant="ghost" size="icon" className="h-8 w-8" onClick={()=>toggleStar(selectedEmail)}><Star className={`h-4 w-4 ${selectedEmail.is_starred?'fill-current text-amber-500':'text-slate-400'}`}/></Button><Button variant="ghost" size="icon" className="h-8 w-8" onClick={()=>moveToFolder(selectedEmail,'archive')}><Archive className="h-4 w-4 text-slate-400"/></Button><Button variant="ghost" size="icon" className="h-8 w-8" onClick={()=>moveToFolder(selectedEmail,'trash')}><Trash2 className="h-4 w-4 text-slate-400"/></Button></div></div><EmailReadingPane email={selectedEmail} threadEmails={threadEmails} onBack={()=>{setSelectedEmailId(null);setFullViewEmail(false);}} onReply={handleReply} onForward={handleForward} onStar={toggleStar} onArchive={e=>moveToFolder(e,'archive')} onDelete={e=>moveToFolder(e,'trash')} onMarkRead={markRead} sending={sending} isFullView={fullViewEmail} onToggleFullView={()=>setFullViewEmail(v=>!v}/></>:<div className="hidden h-full flex-col items-center justify-center bg-gradient-to-br from-slate-50 to-white px-8 text-center md:flex"><div className="mb-5 flex h-16 w-16 items-center justify-center rounded-3xl bg-white shadow-sm ring-1 ring-slate-200"><Sparkles className="h-7 w-7 text-slate-500"/></div><h2 className="text-lg font-semibold">Your inbox, organized</h2><p className="mt-2 max-w-sm text-sm leading-6 text-slate-500">Select a conversation to read, reply, forward, archive or connect it to your client workflow.</p><Button className="mt-5 rounded-xl bg-slate-900 text-white" onClick={()=>{setComposeInitial({to:'',name:'',subject:'',body:''});setComposeOpen(true);}}><Plus className="mr-2 h-4 w-4"/>Compose a message</Button></div>}</section>}
    </div><footer className="hidden shrink-0 items-center justify-between border-t border-slate-200 bg-white px-4 py-2 text-[10px] text-slate-400 md:flex"><span className="flex items-center gap-1.5"><ShieldCheck className="h-3 w-3 text-emerald-500"/>Mailbox access is permission-controlled</span><span className="flex items-center gap-1.5"><Clock3 className="h-3 w-3"/>{activeAccount==='gmail'?(syncingGmail?'Syncing Gmail…':'Gmail sync ready'):'Connected mail ready'}</span></footer></div><ComposeDialog open={composeOpen} onOpenChange={setComposeOpen} onSend={handleComposeSend} onSaveDraft={handleSaveDraft} onDiscard={()=>{}} sending={sending} initialTo={composeInitial.to} initialName={composeInitial.name} initialSubject={composeInitial.subject} initialBody={composeInitial.body}/></div>;
}
