import React, { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Search, RefreshCw, Users, Eye, Loader2 } from 'lucide-react';
import { toast } from '@/hooks/use-toast';

type Subscriber = {
  subscription_number:string; subscriber_name:string; estate_name:string; estate_code:string;
  client_id:string|null; order_id:string|null; subscription_status:string; payment_plan:string|null;
  subscription_amount:number; subscribed_at:string; client_email:string|null; plot_count:number;
  order_total:number; amount_paid:number; outstanding_balance:number;
};

const money = (value:number) => `₦${Number(value || 0).toLocaleString('en-NG')}`;

const AdminEstateSubscribers: React.FC = () => {
  const [rows,setRows]=useState<Subscriber[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[estate,setEstate]=useState('all'),[selected,setSelected]=useState<Subscriber|null>(null);
  const load=async()=>{setLoading(true);try{const {data,error}=await supabase.rpc('admin_get_estate_subscribers',{_search:query.trim()||null,_estate_code:estate==='all'?null:estate});if(error)throw error;setRows((data||[]) as Subscriber[]);}catch(e:any){console.error(e);toast({title:'Could not load subscribers',description:e?.message||'Please try again.',variant:'destructive'});}finally{setLoading(false);}};
  useEffect(()=>{load();},[estate]);
  const estates=useMemo(()=>Array.from(new Map(rows.map(r=>[r.estate_code,r.estate_name])).entries()),[rows]);
  return <Card className="border-white/10 bg-slate-950 text-white shadow-xl dark:bg-slate-950 dark:text-white light:bg-white light:text-slate-900">
    <CardHeader className="border-b border-white/10 bg-white/[0.03]">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><Users className="h-5 w-5 text-primary"/> Estate Subscribers <Badge className="bg-primary/20 text-primary">{rows.length}</Badge></CardTitle><p className="mt-1 text-sm text-slate-300 dark:text-slate-300 light:text-slate-600">Search and review subscribers, plots, payments and outstanding balances.</p></div><Button variant="ghost" size="icon" onClick={load} disabled={loading} className="text-slate-300 hover:bg-white/10 hover:text-white dark:text-slate-300 dark:hover:text-white light:text-slate-700 light:hover:text-slate-950"><RefreshCw className={loading?'h-4 w-4 animate-spin':'h-4 w-4'}/></Button></div>
      <div className="mt-4 grid grid-cols-1 gap-2 md:grid-cols-2"><div className="relative"><Search className="absolute left-2 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400"/><Input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Subscriber name, subscription no., estate or email…" className="pl-8 border-white/10 bg-slate-900 text-white placeholder:text-slate-400 dark:bg-slate-900 dark:text-white light:bg-white light:text-slate-900 light:placeholder:text-slate-500"/></div><select value={estate} onChange={e=>setEstate(e.target.value)} className="rounded-md border border-white/10 bg-slate-900 px-3 text-sm text-white dark:bg-slate-900 dark:text-white light:bg-white light:text-slate-900"><option value="all">All estates</option>{estates.map(([code,name])=><option key={code} value={code}>{code} — {name}</option>)}</select></div>
    </CardHeader>
    <CardContent className="p-0">{loading?<div className="flex justify-center py-12"><Loader2 className="h-6 w-6 animate-spin"/></div>:rows.length===0?<p className="py-10 text-center text-slate-300 dark:text-slate-300 light:text-slate-600">No estate subscribers found.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-white/10 text-slate-300 dark:text-slate-300 light:text-slate-600"><th className="p-3 text-left">Subscriber</th><th className="p-3 text-left">Subscription No.</th><th className="p-3 text-left">Estate</th><th className="p-3 text-left">Plots</th><th className="p-3 text-left">Paid</th><th className="p-3 text-left">Balance</th><th className="p-3 text-left">Plan</th><th className="p-3 text-left">Status</th><th className="p-3"></th></tr></thead><tbody>{rows.map(r=><tr key={r.subscription_number} className="border-b border-white/10 hover:bg-white/[0.04]"><td className="p-3 font-semibold text-white dark:text-white light:text-slate-900"><div>{r.subscriber_name}</div><div className="text-xs font-normal text-slate-300 dark:text-slate-300 light:text-slate-500">{r.client_email||'—'}</div></td><td className="p-3 font-semibold text-primary">{r.subscription_number}</td><td className="p-3 text-white dark:text-white light:text-slate-900">{r.estate_name}</td><td className="p-3 text-white dark:text-white light:text-slate-900">{r.plot_count}</td><td className="p-3 text-white dark:text-white light:text-slate-900">{money(r.amount_paid)}</td><td className="p-3 font-bold text-white dark:text-white light:text-slate-900">{money(r.outstanding_balance)}</td><td className="p-3 text-slate-200 dark:text-slate-200 light:text-slate-700">{r.payment_plan||'—'}</td><td className="p-3"><Badge>{r.subscription_status}</Badge></td><td className="p-3"><Button size="sm" variant="ghost" className="gap-1 text-slate-200 hover:bg-white/10 hover:text-white dark:text-slate-200 dark:hover:text-white light:text-slate-700 light:hover:text-slate-950" onClick={()=>setSelected(r)}><Eye className="h-4 w-4"/> View</Button></td></tr>)}</tbody></table></div>}</CardContent>
    <Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="max-w-2xl border-white/10 bg-slate-950 text-white dark:bg-slate-950 dark:text-white light:bg-white light:text-slate-900"><DialogHeader><DialogTitle>{selected?.subscriber_name}</DialogTitle><DialogDescription className="text-slate-300 dark:text-slate-300 light:text-slate-600">{selected?.subscription_number} • {selected?.estate_name}</DialogDescription></DialogHeader>{selected&&<div className="grid grid-cols-1 gap-4 text-sm md:grid-cols-2"><div><p className="text-slate-300 dark:text-slate-300 light:text-slate-500">Subscriber</p><p className="font-semibold">{selected.subscriber_name}</p></div><div><p className="text-slate-300 dark:text-slate-300 light:text-slate-500">Email</p><p>{selected.client_email||'—'}</p></div><div><p className="text-slate-300 dark:text-slate-300 light:text-slate-500">Plots</p><p className="font-semibold">{selected.plot_count}</p></div><div><p className="text-slate-300 dark:text-slate-300 light:text-slate-500">Order Total</p><p>{money(selected.order_total)}</p></div><div><p className="text-slate-300 dark:text-slate-300 light:text-slate-500">Amount Paid</p><p>{money(selected.amount_paid)}</p></div><div><p className="text-slate-300 dark:text-slate-300 light:text-slate-500">Outstanding Balance</p><p className="text-xl font-extrabold">{money(selected.outstanding_balance)}</p></div><div><p className="text-slate-300 dark:text-slate-300 light:text-slate-500">Payment Plan</p><p>{selected.payment_plan||'—'}</p></div><div><p className="text-slate-300 dark:text-slate-300 light:text-slate-500">Status</p><p>{selected.subscription_status}</p></div><div className="md:col-span-2"><p className="text-slate-300 dark:text-slate-300 light:text-slate-500">Order ID</p><p className="break-all">{selected.order_id||'—'}</p></div></div>}</DialogContent></Dialog>
  </Card>;
};
export default AdminEstateSubscribers;
