import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { requireEnv } from "../_shared/gmail.ts";
const decode=(v:string)=>{try{const s=v.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-v.length%4)%4);return decodeURIComponent(escape(atob(s)))}catch{return''}};
const accounts=(v:string|null|undefined)=>(v||'').split(/[,;\n]+/).map(x=>x.trim().toLowerCase()).filter(Boolean);
const redirect=(app:string,p:Record<string,string>)=>{const u=new URL(`${app}/admin-console`);u.searchParams.set('tab','emails');Object.entries(p).forEach(([k,v])=>u.searchParams.set(k,v));return new Response(null,{status:302,headers:{Location:u.toString()}})};
Deno.serve(async(req)=>{const q=new URL(req.url).searchParams,code=q.get('code'),state=q.get('state'),oauthError=q.get('error');const url=Deno.env.get('SUPABASE_URL')!,app=Deno.env.get('APP_URL')||'https://www.bridgeforthomes.com';const svc=createClient(url,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);if(oauthError)return redirect(app,{gmail_error:oauthError});if(!code||!state)return redirect(app,{gmail_error:'missing_code_or_state'});try{
 const {data:st,error:se}=await svc.from('gmail_oauth_state').select('*').eq('state',state).eq('used',false).maybeSingle();if(se||!st)return redirect(app,{gmail_error:'invalid_or_expired_state'});if(Date.now()-new Date(st.created_at).getTime()>10*60*1000)return redirect(app,{gmail_error:'expired_state'});
 const dot=state.lastIndexOf('.'),mailboxEmail=dot>0?decode(state.slice(dot+1)).trim().toLowerCase():'';if(!mailboxEmail)return redirect(app,{gmail_error:'mailbox_missing_from_state'});await svc.from('gmail_oauth_state').update({used:true}).eq('state',state);
 const {data:access,error:ae}=await svc.rpc('user_mailbox_access',{_user_id:st.requested_by,_mailbox_email:mailboxEmail,_provider:'gmail'});if(ae||!access)return redirect(app,{gmail_error:'mailbox_not_authorized'});
 const {data:mb,error:me}=await svc.from('admin_mailboxes').select('id,provider_account_id').eq('mailbox_email',mailboxEmail).eq('mailbox_provider','gmail').eq('status','active');if(me)return redirect(app,{gmail_error:'assignment_lookup_failed'});const assigned=[...new Set((mb||[]).flatMap((x:any)=>accounts(x.provider_account_id)))];if(!assigned.length)return redirect(app,{gmail_error:'google_account_not_assigned'});
 const clientId=requireEnv('GOOGLE_CLIENT_ID'),clientSecret=requireEnv('GOOGLE_CLIENT_SECRET'),redirectUri=`${url}/functions/v1/gmail-oauth-callback`;const tr=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:clientId,client_secret:clientSecret,redirect_uri:redirectUri,grant_type:'authorization_code'})});const td=await tr.json();if(!tr.ok)return redirect(app,{gmail_error:'token_exchange_failed'});
 const pr=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/profile',{headers:{Authorization:`Bearer ${td.access_token}`}});const pd=await pr.json();const googleEmail=String(pd.emailAddress||'').trim().toLowerCase();if(!pr.ok||!googleEmail)return redirect(app,{gmail_error:'profile_fetch_failed'});if(!assigned.includes(googleEmail))return redirect(app,{gmail_error:'google_account_not_assigned',gmail_attempted_email:googleEmail});if(!td.refresh_token)return redirect(app,{gmail_error:'no_refresh_token',gmail_attempted_email:googleEmail});
 const mailboxId=mb?.[0]?.id;if(!mailboxId)return redirect(app,{gmail_error:'mailbox_record_missing'});const expiresAt=new Date(Date.now()+td.expires_in*1000).toISOString();const {data:existing}=await svc.from('gmail_oauth_tokens').select('id,refresh_token').eq('mailbox_id',mailboxId).ilike('google_account_email',googleEmail).maybeSingle();const payload={email:mailboxEmail,mailbox_id:mailboxId,google_account_email:googleEmail,access_token:td.access_token,refresh_token:td.refresh_token||existing?.refresh_token,expires_at:expiresAt,connected_by:st.requested_by,is_active:true,updated_at:new Date().toISOString()};
 if(existing){const {error:e}=await svc.from('gmail_oauth_tokens').update(payload).eq('id',existing.id);if(e)return redirect(app,{gmail_error:'storage_failed'});}else{const {error:e}=await svc.from('gmail_oauth_tokens').insert(payload);if(e)return redirect(app,{gmail_error:'storage_failed'});}
 return redirect(app,{gmail_connected:'1',gmail_email:mailboxEmail,gmail_google_account:googleEmail});
 }catch(e){console.error('gmail-oauth-callback',e);return redirect(app,{gmail_error:'unexpected_error'});}});
