DROP POLICY IF EXISTS super_admin_all_select ON public.admin_emails;
DROP POLICY IF EXISTS super_admin_all_insert ON public.admin_emails;
DROP POLICY IF EXISTS super_admin_all_update ON public.admin_emails;
DROP POLICY IF EXISTS super_admin_all_delete ON public.admin_emails;
CREATE POLICY global_admin_all_select ON public.admin_emails FOR SELECT TO authenticated USING (public.is_global_admin(auth.uid()) OR public.user_mailbox_access(auth.uid(), to_email) OR public.user_mailbox_access(auth.uid(), from_email));
CREATE POLICY global_admin_all_insert ON public.admin_emails FOR INSERT TO authenticated WITH CHECK (public.is_global_admin(auth.uid()) OR public.user_mailbox_access(auth.uid(), to_email) OR public.user_mailbox_access(auth.uid(), from_email));
CREATE POLICY global_admin_all_update ON public.admin_emails FOR UPDATE TO authenticated USING (public.is_global_admin(auth.uid()) OR public.user_mailbox_access(auth.uid(), to_email) OR public.user_mailbox_access(auth.uid(), from_email)) WITH CHECK (public.is_global_admin(auth.uid()) OR public.user_mailbox_access(auth.uid(), to_email) OR public.user_mailbox_access(auth.uid(), from_email));
CREATE POLICY global_admin_all_delete ON public.admin_emails FOR DELETE TO authenticated USING (public.is_global_admin(auth.uid()) OR public.user_mailbox_access(auth.uid(), to_email) OR public.user_mailbox_access(auth.uid(), from_email));
DROP POLICY IF EXISTS email_accounts_access_own ON public.email_accounts;
DROP POLICY IF EXISTS email_accounts_write_own ON public.email_accounts;
DROP POLICY IF EXISTS super_admin_all_select ON public.email_accounts;
DROP POLICY IF EXISTS super_admin_all_insert ON public.email_accounts;
DROP POLICY IF EXISTS super_admin_all_update ON public.email_accounts;
DROP POLICY IF EXISTS super_admin_all_delete ON public.email_accounts;
CREATE POLICY email_accounts_access_authorized ON public.email_accounts FOR SELECT TO authenticated USING (auth.uid() = user_id OR public.is_global_admin(auth.uid()) OR public.user_mailbox_access(auth.uid(), mailbox_email, provider));
CREATE POLICY email_accounts_write_authorized ON public.email_accounts FOR ALL TO authenticated USING (auth.uid() = user_id OR public.is_global_admin(auth.uid()) OR public.user_has_permission(auth.uid(), 'admin:manage_mailboxes')) WITH CHECK (auth.uid() = user_id OR public.is_global_admin(auth.uid()) OR public.user_has_permission(auth.uid(), 'admin:manage_mailboxes'));
DROP POLICY IF EXISTS super_admin_all_select ON public.email_sessions;
DROP POLICY IF EXISTS super_admin_all_insert ON public.email_sessions;
DROP POLICY IF EXISTS super_admin_all_update ON public.email_sessions;
DROP POLICY IF EXISTS super_admin_all_delete ON public.email_sessions;
CREATE POLICY global_admin_all_select ON public.email_sessions FOR SELECT TO authenticated USING (public.is_global_admin(auth.uid()) OR (auth.uid() = user_id AND public.user_mailbox_access(auth.uid(), mailbox_email, provider)));
CREATE POLICY global_admin_all_insert ON public.email_sessions FOR INSERT TO authenticated WITH CHECK (public.is_global_admin(auth.uid()) OR (auth.uid() = user_id AND public.user_mailbox_access(auth.uid(), mailbox_email, provider)));
CREATE POLICY global_admin_all_update ON public.email_sessions FOR UPDATE TO authenticated USING (public.is_global_admin(auth.uid()) OR (auth.uid() = user_id AND public.user_mailbox_access(auth.uid(), mailbox_email, provider))) WITH CHECK (public.is_global_admin(auth.uid()) OR (auth.uid() = user_id AND public.user_mailbox_access(auth.uid(), mailbox_email, provider)));
CREATE POLICY global_admin_all_delete ON public.email_sessions FOR DELETE TO authenticated USING (public.is_global_admin(auth.uid()) OR (auth.uid() = user_id AND public.user_mailbox_access(auth.uid(), mailbox_email, provider)));
