INSERT INTO public.roles (name, display_name, description) VALUES ('user','User','Registered account holder who has not yet purchased property or registered as a PBO'),('client','Client','Customer who has a completed property purchase/payment'),('pbo','PBO','PWAN Business Owner registered to the PBO programme') ON CONFLICT (name) DO UPDATE SET display_name=EXCLUDED.display_name,description=EXCLUDED.description,updated_at=now();
CREATE OR REPLACE FUNCTION public.block_role_updates_on_users() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ BEGIN IF NEW.role IS DISTINCT FROM OLD.role THEN IF public.is_global_admin(auth.uid()) OR current_setting('bridgefort.sync_role',true)='1' THEN RETURN NEW; END IF; RAISE EXCEPTION 'Updating users.role is restricted to Admin-Dir and Super_Admin'; END IF; RETURN NEW; END; $function$;
CREATE OR REPLACE FUNCTION public.sync_business_user_role(_user_id uuid) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE next_role text:='user'; is_pbo_user boolean:=false; has_completed_purchase boolean:=false; BEGIN IF _user_id IS NULL THEN RETURN NULL; END IF; SELECT COALESCE(p.is_pbo,false) INTO is_pbo_user FROM public.profiles p WHERE p.id=_user_id; SELECT EXISTS(SELECT 1 FROM public.payments pay WHERE pay.user_id=_user_id AND lower(coalesce(pay.status,'')) IN ('completed','successful','success','approved','paid','active')) INTO has_completed_purchase; IF is_pbo_user THEN next_role:='pbo'; ELSIF has_completed_purchase THEN next_role:='client'; END IF; PERFORM set_config('bridgefort.sync_role','1',true); UPDATE public.users SET role=next_role,updated_at=now() WHERE id=_user_id AND NOT EXISTS(SELECT 1 FROM public.admin_roles ar WHERE ar.user_id=_user_id AND ar.role_name IN ('admin_dir','super_admin','admin_adm','admin_acct','admin_sales','admin_cs','admin_legal','admin_it') AND (ar.expires_at IS NULL OR ar.expires_at>now())); RETURN next_role; END; $function$;
REVOKE ALL ON FUNCTION public.sync_business_user_role(uuid) FROM anon,authenticated; GRANT EXECUTE ON FUNCTION public.sync_business_user_role(uuid) TO service_role;
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ BEGIN INSERT INTO public.profiles(id,first_name,last_name) VALUES(NEW.id,COALESCE(NEW.raw_user_meta_data->>'first_name',''),COALESCE(NEW.raw_user_meta_data->>'last_name','')) ON CONFLICT(id) DO NOTHING; INSERT INTO public.users(id,email,role) VALUES(NEW.id,NEW.email,'user') ON CONFLICT(id) DO UPDATE SET email=EXCLUDED.email; RETURN NEW; END; $function$;
CREATE OR REPLACE FUNCTION public.sync_role_after_profile_change() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ BEGIN PERFORM public.sync_business_user_role(NEW.id); RETURN NEW; END; $function$;
CREATE OR REPLACE FUNCTION public.sync_role_after_payment_change() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ BEGIN PERFORM public.sync_business_user_role(NEW.user_id); RETURN NEW; END; $function$;
DROP TRIGGER IF EXISTS trg_sync_role_after_profile_change ON public.profiles; CREATE TRIGGER trg_sync_role_after_profile_change AFTER INSERT OR UPDATE OF is_pbo ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.sync_role_after_profile_change();
DROP TRIGGER IF EXISTS trg_sync_role_after_payment_change ON public.payments; CREATE TRIGGER trg_sync_role_after_payment_change AFTER INSERT OR UPDATE OF status ON public.payments FOR EACH ROW EXECUTE FUNCTION public.sync_role_after_payment_change();
