// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wviealbcyyaaptthoahu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2aWVhbGJjeXlhYXB0dGhvYWh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzQ2OTgsImV4cCI6MjA2MTExMDY5OH0.pg3erdE72RddksGGB1LdaT_MV7EU_NOcMFIe35gXHlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);